apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiZ2VqaW9rYSIsInBhc3N3b3JkIjoiJWdlMjYzMTIiLCJlbWFpbCI6ImdlLnR6aW9rYXNAZ21haWwuY29tIiwiYXV0aCI6IloyVnFhVzlyWVRvbFoyVXlOak14TWc9PSJ9fX0=
