# network-prod-oai-s6a-v1.yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: prod-oai-cass-v1
  namespace: default
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "macvlan",
      "master": "ens33",
      "mode": "bridge",
      "ipam": {
          "type": "static",
          "subnet": "192.168.62.160/27",
          "gateway": "192.168.62.161",
          "routes": [
              {
                  "dst": "0.0.0.0/0"
              }
          ]
      }
  }'
