# apiVersion: k8s.cni.cncf.io/v1
# kind: NetworkAttachmentDefinition
# metadata:
  # name: prod-oai-s6a-v1
  # namespace: default
# spec:
  # config: |
    # {
      # "cniVersion": "0.4.0",
      # "type": "macvlan",
      # "master": "ens33",
      # "mode": "bridge",
      # "ipam": {
          # "type": "static",
          # "subnet": "192.168.62.0/27",
          # "addresses": [
              # {
                  # "address": "192.168.62.2/27",
                  # "gateway": "192.168.62.1"
              # },
              # {
                  # "address": "192.168.62.3/27",
                  # "gateway": "192.168.62.1"
              # }
          # ],
          # "routes": [
              # {
                  # "dst": "0.0.0.0/0"
              # }
          # ]
      # }
    # }

# apiVersion: k8s.cni.cncf.io/v1
# kind: NetworkAttachmentDefinition
# metadata:
  # name: prod-oai-s6a-v1
  # namespace: default
# spec:
  # config: '{
      # "cniVersion": "0.4.0",
      # "type": "macvlan",
      # "capabilities": {"ips": true},
      # "master": "ens33",
      # "mode": "bridge",
      # "ipam": {
          # "type": "static",
          # "subnet": "192.168.62.0/27",
          # "addresses": [
             # {
                 # "address": "192.168.62.2/27",
                 # "gateway": "192.168.62.1"
             # },
             # {
                 # "address": "192.168.62.3/27",
                 # "gateway": "192.168.62.1"
             # }
              # 
          # ],
          # "routes": [
              # {
                  # "dst": "0.0.0.0/0"
              # }
          # ]
      # }
  # }'

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: prod-oai-s6a-v1
  namespace: default
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "macvlan",
      "master": "ens33",
      "mode": "bridge",
      "ipam": {
          "type": "static",
          "subnet": "192.168.62.0/27",
          "gateway": "192.168.62.1",
          "routes": [
              {
                  "dst": "0.0.0.0/0"
              }
          ]
      }
  }'
