apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-oai-enb-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-oai-enb-v1
  template:
    metadata:
      labels:
        app: prod-oai-enb-v1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "prod-oai-s1c-v1"}, {"name": "prod-oai-s1u-v1"}]'
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: prod-oai-enb-v1
        image: registry.gitlab.com/gejioka/oai-images-test/prod-oai-enb-v1:1.0.0
        command: ["/bin/bash", "-c", "sleep infinity"]
        volumeMounts:
        - name: oai-enb-volume
          mountPath: /oai-enb
        - name: dev-volume
          mountPath: /dev
        securityContext:
          privileged: true
      volumes:
      - name: oai-enb-volume
        hostPath:
          path: /home/ubuntu/openair-enb/
          type: Directory
      - name: dev-volume
        hostPath:
          path: /dev
