apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-oai-mme-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-oai-mme-v1
  template:
    metadata:
      labels:
        app: prod-oai-mme-v1
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "prod-oai-s6a-v1",
              "interface": "eth4",
              "ips": ["192.168.62.2/27"]
            },
            {
              "name": "prod-oai-s11c-v1",
              "interface": "eth2",
              "ips": ["192.168.62.34/27"]
            },
            {
              "name": "prod-oai-s1c-v1",
              "interface": "eth3",
              "ips": ["192.168.62.130/27"]
            },
            {
              "name": "prod-oai-external",
              "interface": "eth1",
              "ips": ["192.168.62.194/27"]
            }
          ]
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: prod-oai-mme-v1
          image: 'registry.gitlab.com/gejioka/oai-images-test/dev_mme_v1:1.0.1'
          securityContext:
            privileged: true
          command:
          - sh
          - -c
          - |
            ip link set eth0 down
            ip link set eth0 name eth5
            # ip link set eth2 up
            ip link set eth1 down
            ip link set eth1 name eth0
            ip link set eth0 up
            ip link set eth2 down
            ip link set eth2 name eth1
            ip link set eth1 up
            ip link set eth3 down
            ip link set eth3 name eth2
            ip link set eth2 up
            ip link set eth4 down
            ip link set eth4 name eth3
            ip link set eth3 up
            ip link set eth5 name eth4
            ip link set eth4 up
            sleep infinity
          volumeMounts:
            - mountPath: /oai-mme
              name: oai-mme-volume
          securityContext:
            privileged: true
      volumes:
        - name: oai-mme-volume
          hostPath:
            path: /home/ubuntu/oai-core-k8s/component/oai-mme/
            type: DirectoryOrCreate
