apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-oai-spgwc-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-oai-spgwc-v1
  template:
    metadata:
      labels:
        app: prod-oai-spgwc-v1
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "prod-oai-s11c-v1",
              "interface": "eth1",
              "ips": ["192.168.62.35/27"]
            },
            {
              "name": "prod-oai-sx-v1",
              "interface": "eth2",
              "ips": ["192.168.62.66/27"]
            }
          ]
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: prod-oai-spgwc-v1
        image: registry.gitlab.com/gejioka/oai-images-test/dev_spgwc_v1:1.0.0
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          ifconfig eth0 down
          ifconfig eth0 name eth3
          ifconfig eth3 up
          ifconfig eth1 down
          ifconfig eth1 name eth0
          ifconfig eth0 up
          ifconfig eth2 down
          ifconfig eth2 name eth1
          ifconfig eth1 up
          ifconfig eth3 down
          ifconfig eth3 name eth2
          ifconfig eth2 up
          sleep infinity
        volumeMounts:
        - mountPath: /oai-spgwc
          name: oai-spgwc-volume
        # securityContext:
          # privileged: true
      volumes:
      - name: oai-spgwc-volume
        hostPath:
          path: /home/ubuntu/oai-core-k8s/component/oai-spgwc/
          type: DirectoryOrCreate
