apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-cassandra-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-cassandra-v1
  template:
    metadata:
      labels:
        app: prod-cassandra-v1
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: prod-cassandra-v1
        image: registry.gitlab.com/gejioka/oai-images-test/dev_cassandra_v1:1.0.0
        securityContext:
          privileged: true
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: CASSANDRA_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: prod-cassandra-configmap
              key: CASSANDRA_CLUSTER_NAME
        - name: CASSANDRA_ENDPOINT_SNITCH
          valueFrom:
            configMapKeyRef:
              name: prod-cassandra-configmap
              key: CASSANDRA_ENDPOINT_SNITCH
        command:
        - sh
        - -c
        - |
          # ip addr delete 10.85.0.128/16 dev eth0
          # ip addr add 192.168.62.163/27 dev eth0
          # ip link set dev eth0 up
          # ip route add default via 192.168.62.161 dev eth0
          # ip link set eth0 down
          # ip link set eth0 name eth1
          # ip link set eth1 up
          # ip link set eth2 down
          # ip link set eth2 name eth0
          # ip link set eth0 up
          # ip link set eth1 down
          sleep infinity
