# network-prod-oai-sx-v1.yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: prod-oai-sx-v1
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
          "type": "static",
          "subnet": "192.168.62.64/27",
          "gateway": "192.168.62.65",
          "routes": [
              {
                  "dst": "0.0.0.0/0"
              }
          ]
      }
    }
